// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaxN37qxkQ6pJikKkip_3p8scViDS_OVA',
    appId: '1:90611484556:web:c4783b9180a8e71f3cf8a9',
    messagingSenderId: '90611484556',
    projectId: 'shop01-a8a0a',
    authDomain: 'shop01-a8a0a.firebaseapp.com',
    storageBucket: 'shop01-a8a0a.firebasestorage.app',
    measurementId: 'G-3L756M83JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSIGUvBSMcM_tbn3MRc3VtEr-HPSjGt5A',
    appId: '1:90611484556:android:1f230cee1773166a3cf8a9',
    messagingSenderId: '90611484556',
    projectId: 'shop01-a8a0a',
    storageBucket: 'shop01-a8a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-12adDW-Ct0VkLacbPWSeAybDHgy0dFM',
    appId: '1:90611484556:ios:5a7d03f6b60873793cf8a9',
    messagingSenderId: '90611484556',
    projectId: 'shop01-a8a0a',
    storageBucket: 'shop01-a8a0a.firebasestorage.app',
    iosBundleId: 'com.example.fluttershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-12adDW-Ct0VkLacbPWSeAybDHgy0dFM',
    appId: '1:90611484556:ios:5a7d03f6b60873793cf8a9',
    messagingSenderId: '90611484556',
    projectId: 'shop01-a8a0a',
    storageBucket: 'shop01-a8a0a.firebasestorage.app',
    iosBundleId: 'com.example.fluttershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaxN37qxkQ6pJikKkip_3p8scViDS_OVA',
    appId: '1:90611484556:web:3a912b2c5336070a3cf8a9',
    messagingSenderId: '90611484556',
    projectId: 'shop01-a8a0a',
    authDomain: 'shop01-a8a0a.firebaseapp.com',
    storageBucket: 'shop01-a8a0a.firebasestorage.app',
    measurementId: 'G-X0VTMVMLQ6',
  );
}
